steps:
- name: python:3.11
  entrypoint: bash
  args:
    - -c
    - |
      pip install --upgrade pip
      pip install -r requirements.txt
      python streaming_pipeline.py

options:
  logging: CLOUD_LOGGING_ONLY
